version: '3.1'
services:
  dictionary:
    image: 'hachiko2k/hachiko-dictionary'
    ports:
      - "8888:8888"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/hachiko-dictionary
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./src/main/resources/schema.sql:/data/schema.sql
      - ./src/main/resources/data.sql:/data/data.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hachiko-dictionary
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5