version: "3.8"

services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27018:27017"
    volumes:
      - ./src/main/resources/data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./src/main/resources/data/words.json:/words.json:ro

  dictionary:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dictionary
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.data.mongodb.uri" : "mongodb://root:example@mongodb:27017/dictionary?authSource=admin"
      }'
